### ISSUE TITLE
Enhancement Request: Support more than one tap

### ISSUE THREAD

**Issue by dboyd13** [patfreeman/alexa-app-kegbot#5]
Hi -

Was wondering if you'd consider an enhancement to support more than one Kegbot tap?

Let me know if you need any sample json.

Thanks

**Comment by patfreeman** [comment]
Do you have any thoughts on how to do that? New utterances:
What's on tap number one?
How much is left on tap number two?

Then have the existing utterances tell about all taps.

It should be easy enough to do.

**Comment by dboyd13** [comment]
My thoughts. 

Utterance: How much beer is left?

Response (repeat per tap): "there is x % of beer x left"

Utterance: How much beer in tap one/left tap/right tap

Also. I've customized your code a bit on my end to do the following relating to volume:

"How much beer is left" - response in Litres
"How many pints left" - response in pints
"What % is left" - response as per your original.

**Comment by patfreeman** [comment]
Pull request?

**Comment by dboyd13** [comment]
Sure thing. Will need to clean it up a bit first - was just a bit of messy hacking.  Haven't done any work on the multi tap stuff yet.

**Comment by patfreeman** [comment]
I added multiple tap support in commit https://github.com/patfreeman/alexa-app-kegbot/commit/a404d67e6022f4177b189a44b30d80fff8e59126. I felt that left and right are too arbitrary to use as identifiers and kept to numbers.

I'd probably want the default volume units to be in line with the default configured in kegbot. Not sure how to get that from the API though.

**Comment by dboyd13** [comment]
Multiple tap support working. Thanks.

Regarding the customizations I've done my end for:
- "How much beer is left" - response in Litres
- "How many pints left" - response in pints
- "What % is left" - response as per your original.

Before I clean this up, and do a pull request into your main branch, wanted to make sure we are in agreement on approach - what I am proposing:

**General Volume**

Utterances: 
Volume	how much beer is left
Volume	how much is left
Volume	how much beer is there
Volume	how much is there
Volume	how much is left in keg {TapNumber}
Volume	how much beer is left in keg {TapNumber}
Volume	how much is there in keg {TapNumber}
Volume	how much beer is there in keg {TapNumber}
Volume	how much is left in tap {TapNumber}
Volume	how much beer is left in tap {TapNumber}
Volume	how much is there in tap {TapNumber}
Volume	how much beer is there in tap {TapNumber}
Volume	how much is left in keg number {TapNumber}
Volume	how much beer is left in keg number {TapNumber}
Volume	how much is there in keg number {TapNumber}
Volume	how much beer is there in keg number {TapNumber}
Volume	how much is left in tap number {TapNumber}
Volume	how much beer is left in tap number {TapNumber}
Volume	how much is there in tap number {TapNumber}
Volume	how much beer is there in tap number {TapNumber}

Intent: 'Volume' - modify to respond in macro absolutes (e.g. Litres/Gallons). Also do not see any API call 
to get user preferred volume units, so may have to be a config.js item

**Percent remaining**

Utterances: 
VolumePercent	what percent is left
VolumePercent	what percentage is left
VolumePercent	what percent is left in the keg
VolumePercent	what percentage is left in the keg
VolumePercent	what percent is the keg at
VolumePercent	what percentage is the keg at
VolumePercent	what is the keg percentage
VolumePercent	what is the beer percentage
VolumePercent	what percent is left in keg {TapNumber}
VolumePercent	what percentage is left in keg {TapNumber}
VolumePercent	what percent is left in tap {TapNumber}
VolumePercent	what percentage is left in tap {TapNumber}
VolumePercent	what percent is left in keg number {TapNumber}
VolumePercent	what percentage is left in keg number {TapNumber}
VolumePercent	what percent is left in tap number {TapNumber}
VolumePercent	what percentage is left in tap number {TapNumber}
VolumePercent	what is the keg percentage in keg {TapNumber}
VolumePercent	what is the beer percentage in keg {TapNumber}
VolumePercent	what is the keg percentage in tap {TapNumber}
VolumePercent	what is the beer percentage in tap {TapNumber}
VolumePercent	what is the keg percentage in keg number {TapNumber}
VolumePercent	what is the beer percentage in keg number {TapNumber}
VolumePercent	what is the keg percentage in tap number {TapNumber}
VolumePercent	what is the beer percentage in tap number {TapNumber}

Intent: 'VolumePercent' - use the existing code you have assigned to Volume intent

**Pints remaining**

Utterances:
VolumePint how many pints left
VolumePint how many pints left in tap number {TapNumber}
VolumePint how many pints left in keg number {TapNumber}

Intent: 'VolumePint' - configure US/UK pint size preference and constants via config.js item

**Comment by patfreeman** [comment]
It makes sense to split the Volume and VolumePercent intents, unless the existence of the word 'percentage' can be an optional slot.

Being in one of the countries that defaults to the inferior empirical units, I think that the Volume intent should follow the preference configured in config.js. Then add a custom slot for pints / litres to alter the response. So the utterances would look like:

Volume how much beer is left in {pints|VolumeUnits}
...
Volume how many {litres|VolumeUnits} are left in tap number {TapNumber}
...
etc.

**Comment by patfreeman** [comment]
Requires a custom slot, but it all works in one intent.
